# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20170210_0857'),
        ('rango', '0006_userprofile'),
    ]

    operations = [
    ]
